english-docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/en/*"
          - "docs/en/**"

workflows:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/*"
          - ".github/workflows/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"

docs-configuration:
  - changed-files:
      - any-glob-to-any-file:
          - "**/.vitepress/**"

lock-file:
  - changed-files:
      - any-glob-to-any-file:
          - "pnpm-lock.yaml"
